channels:
  - conda-forge

dependencies:
  - python=3.9.13               # https://pyreadiness.org/3.9/ 
  - pip=22.1.2                  # https://pip.pypa.io/en/stable/news/
  - nodejs=18.15.0
  - pip:
      - rpaframework    # https://rpaframework.org/releasenotes.html
      - rpaframework-assistant
      - robotframework-browser
rccPostInstall:
  - rfbrowser init