on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    container: hajare/rcc:chrome

    steps:
      - uses: actions/checkout@v2
      - name: Install playwright dependencies
        run: |
          apt-get install -y libatk1.0 libatk-bridge2.0 libcups2 libdrm2 libatspi2.0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libnss3 libnspr4 libpango-1.0-0 libcairo2 libasound2 libgstreamer-plugins-base1.0-0 
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
      - name: Start Xvfb and set the display
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
      - name: Run tasks
        run: rcc run
