on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    container: hajare/rcc:latest

    steps:
      - uses: actions/checkout@v2
      - name: run tasks
        run: rcc run
