on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    container: hajare/rcc:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install playwright dependencies
        run: |
          apt-get install -y libatk-bridge2.0-0\                          
          libcups2\                                    
          libdrm2\                                     
          libatspi2.0-0\                               
          libxcomposite1\                              
          libxdamage1\                                 
          libxfixes3\                                  
          libxrandr2\                                  
          libgbm1\                                     
          libxkbcommon0
      - name: Run tasks
        run: rcc run
