on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    container: hajare/rcc:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm and npx
        run: |
          apt-get install npm -y
          npm install -g npx
      - name: Install playwright dependencies
        run: npx playwright install-deps
      - name: Run tasks
        run: rcc run
