on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    container: hajare/rcc:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: npx playwright install-deps 
      - name: Install dependencies
        run: npm install -g npx
      - name: install npx
        run: npx playwright install-deps
      - name: Run tasks
        run: rcc run
